name: Python Tests

on:
  push:
    branches: [ main, add-github-actions ]
  pull_request:
    branches: [ main, add-github-actions ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 5
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.x']
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      shell: bash
    
    - name: Run tests
      run: |
        python -m unittest discover -s testing -p "test_*.py" -v