name: Python Tests

on:
  push:
    branches: [ main, add-github-actions ]
  pull_request:
    branches: [ main, add-github-actions ]
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  test:
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.x']
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
    - name: List directory structure
      run: |
        dir /s
      shell: cmd
      if: runner.os == 'Windows'
        
    - name: Run tests
      run: |
        python -m unittest test_geometric_lib.py
      working-directory: ${{ github.workspace }}